"""
Django settings for pykaraoke project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Twelve-factor config: this file declares *what* to configure, never the
# values. .env is gitignored and never read by Claude (see .claude/settings.json).
# In CI and production, real environment variables take over and read_env()
# is a no-op if no .env file exists.
env = environ.Env(
    DJANGO_DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")


# SECURITY WARNING: keep the secret key used in production secret!
# No default on purpose: a fresh clone with no .env fails loudly at startup
# instead of silently booting on a weak, guessable key.
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG")

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pykaraoke.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pykaraoke.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# No, or empty, DATABASE_URL in .env -> SQLite, zero setup. Set it once
# docker-compose.yml is up to switch to Postgres with no code change.
#
# env.db(..., default=...) only falls back when the key is absent. A key
# present but blank ("DATABASE_URL=") is not absent, so it must be checked
# for explicitly, or the empty string parses into an unusable ENGINE=''.

_database_url = env("DATABASE_URL", default="")
DATABASES = {
    "default": env.db_url_config(_database_url or f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/
#
# Django 6.1 replaced EMAIL_BACKEND/EMAIL_HOST/... with the MAILERS dict.
# django-environ's env.email_url() still only understands the old flat keys,
# so its result is mapped into MAILERS by hand. No, or empty, EMAIL_URL in
# .env -> console backend (mail prints to the terminal instead of sending).
# See DATABASE_URL above: a key present but blank is not absent, so
# default=... alone will not catch it.

_email_url = env("EMAIL_URL", default="")
_email_config = env.email_url_config(_email_url or "consolemail://")
_email_options = {
    "host": _email_config.get("EMAIL_HOST"),
    "port": _email_config.get("EMAIL_PORT"),
    "username": _email_config.get("EMAIL_HOST_USER"),
    "password": _email_config.get("EMAIL_HOST_PASSWORD"),
    "use_tls": _email_config.get("EMAIL_USE_TLS"),
}

MAILERS = {
    "default": {
        "BACKEND": _email_config["EMAIL_BACKEND"],
        "OPTIONS": {k: v for k, v in _email_options.items() if v not in (None, "")},
    },
}


# Security
# https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
#
# Gated on DEBUG so `manage.py check --deploy` is clean today, without
# affecting local development. security.yml runs this check on every push.

SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
